[distros]
    # List of Debian-based distros supported by this config
    debBased = ["debian", "devuan"]

    # List of strict non-systemd distros supported by this config
    # Gentoo should not be in this list!
    strictNonSystemd = ["devuan", "void"]

[sysDirs]
    localBin = ".local/bin"
    scripts = ".Scripti"
    obPipemenus = ".Scripti/openbox-pipemenus"
    localCacheDir = ".cache"

[varia]
    # This is an editor for config files to be invoked via Openbox menu entries
    chezmoiEditorFromMenu = "gvim --nofork"
