[sysDirs]
    localBin = ".local/bin"
    scripts = ".Scripti"
    obPipemenus = ".Scripti/openbox-pipemenus"
    localCacheDir = ".cache"

[varia]
    # This is an editor for config files to be invoked via Openbox menu entries
    chezmoiEditorFromMenu = "gvim --nofork"
