[sysDirs]
    # These paths MUST be relative, because they are also used in .chezmoiexternal.toml as well
    localBin = ".local/Bin"
    scripts = ".local/Scripti"
    obPipemenus = ".local/Scripti/openbox-pipemenus"
    localCache = ".cache"
    backgrounds = ".local/share/backgrounds"

[varia]
    # This is an editor for config files to be invoked via Openbox menu entries
    chezmoiEditorFromMenu = "gvim --nofork"
