# Vim plugin manager
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# Our default GTK and Openbox themes:
# Greylooks, GreylooksGreen, GreylooksHuman and GreylooksOk
{{ range .varia.greylooksThemes }}
[".local/share/themes/{{ . }}"]
    type = "archive"
    url = "https://github.com/vbrand1984/greylooks/archive/master.zip"
    exact = true
    stripComponents = 2
    include = ["greylooks-master/{{ . }}/**"]
    refreshPeriod = "168h"
{{ end }}


{{ if .theSystem.isDebianBased }}

# In Debian-based distros, we need to install obmenu-generator externally
[{{ joinPath (.sysDirs.scripts | trimPrefix .chezmoi.homeDir | trimPrefix "/") .apps.debiansObmenuGeneratorName | quote }}]
    type= "file"
    url = "https://raw.githubusercontent.com/trizen/obmenu-generator/master/obmenu-generator"
    refreshPeriod = "168h"
    executable = false

{{ if not .theSystem.hasSystemd }}
# Pipewire-launcher script from Gentoo to be installed and used in Devuan
[{{ joinPath (.sysDirs.scripts | trimPrefix .chezmoi.homeDir | trimPrefix "/") .apps.devuansPipewireLauncher | quote }}]
    type= "file"
    url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/media-video/pipewire/files/gentoo-pipewire-launcher.in-r3"
    filter.command = "sed"
    filter.args = [ "s/@GENTOO_PORTAGE_EPREFIX@//g" ]
    refreshPeriod = "168h"
    executable = false
{{ end }}

{{ end }}
